name: Test Repository Access

on:
  workflow_dispatch:
  push:

jobs:
  diagnose:
    runs-on: ubuntu-latest
    steps:
      - name: Show context
        run: |
          echo "Repository: ${{ github.repository }}"
          echo "Repository Owner: ${{ github.repository_owner }}"
          echo "Actor: ${{ github.actor }}"
          echo "Event: ${{ github.event_name }}"
          echo "Ref: ${{ github.ref }}"
          
      - name: Test default checkout
        uses: actions/checkout@v4
        continue-on-error: true
        
      - name: Check if default worked
        run: |
          if [ -d ".git" ]; then
            echo "✅ Default checkout worked!"
            ls -la
          else
            echo "❌ Default checkout failed"
          fi
          
      - name: Manual clone with PAT
        if: failure() || !contains(steps.*.outcome, 'success')
        env:
          TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          echo "Trying manual clone..."
          git clone https://x-access-token:${TOKEN}@github.com/${{ github.repository }}.git repo
          if [ -d "repo" ]; then
            echo "✅ Manual clone worked!"
            ls -la repo/
          else
            echo "❌ Manual clone failed"
          fi
